version: '3.8'

services:
  # SQL Server Database
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: altitude-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - altitude-network

  # .NET Backend API
  backend:
    build: 
      context: ../../../altitudeTestAPI/AltitudeApi
      dockerfile: Dockerfile
    container_name: altitude-backend
    depends_on:
      - database
    environment:
      - ConnectionStrings__DefaultConnection=Server=database,1433;Database=AltitudeDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true;
    ports:
      - "5159:8080"
    networks:
      - altitude-network

  # React Frontend
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: altitude-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - altitude-network

volumes:
  sqlserver_data:

networks:
  altitude-network:
    driver: bridge 